wandb_version: 1

seed:
  desc: null
  value: 42
epochs:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 1.0e-05
classifier_lr:
  desc: null
  value: 3.0e-06
batch_size:
  desc: null
  value: 8
adam_betas:
  desc: null
  value:
  - 0.9
  - 0.999
weight_decay:
  desc: null
  value: 0.001
learning_rate_schedule:
  desc: null
  value:
    '100': 0.1
train_dir:
  desc: null
  value: splits
train_mode:
  desc: null
  value: validation
create_validation_set:
  desc: null
  value: 'False'
val_dir:
  desc: null
  value: splits
val_mode:
  desc: null
  value: test
clip_sample_values:
  desc: null
  value: 1
transforms:
  desc: null
  value: null
num_classes:
  desc: null
  value: 8
only_rgb:
  desc: null
  value: 0
rgb_plus_s1:
  desc: null
  value: 0
dataloader_workers:
  desc: null
  value: 8
s1_input_channels:
  desc: null
  value: 2
s2_input_channels:
  desc: null
  value: 13
train_used_data_fraction:
  desc: null
  value: 1
image_px_size:
  desc: null
  value: 224
cover_all_parts_validation:
  desc: null
  value: 1
cover_all_parts_train:
  desc: null
  value: 0
balanced_classes_train:
  desc: null
  value: 1
balanced_classes_validation:
  desc: null
  value: 0
s1_normalization_fixed:
  desc: null
  value: 1
simclr_dataset:
  desc: null
  value: 0
out_dim:
  desc: null
  value: 128
model:
  desc: null
  value: DoubleSwinTransformerSegmentation
base_model:
  desc: null
  value: resnet18
target:
  desc: null
  value: dfc
finetuning:
  desc: null
  value: 0
checkpoint:
  desc: null
  value: checkpoints/swin_t.pth
embedding_size:
  desc: null
  value: 256
wandb_project:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691488527.126866
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.15.2
      8:
      - 5
